# These are supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (requires setting up at https://github.com/sponsors)
github: Hmbown

# Uncomment and configure any of the following platforms you want to use:

# Custom funding URLs (e.g., PayPal, Patreon, Ko-fi, etc.)
# custom: ['https://your-donation-url.com', 'https://patreon.com/yourname']

# Patreon
# patreon: your-patreon-username

# Open Collective
# open_collective: your-org-name

# Ko-fi
# ko_fi: your-ko-fi-username

# Buy Me a Coffee
# buy_me_a_coffee: your-username

# Liberapay
# liberapay: your-username

# Tidelift
# tidelift: platform/package-name
